### ISSUE TITLE
Code generator cannot generate header with libclang 9 installed

### ISSUE THREAD

**Issue by cblichmann** [google/sandboxed-api#32]
Building on Debian 10 "Buster". Shout out to #29, which will also touch this.

Confirmed working with"
* `libclang1-6.0`/`libclang-6.0-dev`
* `libclang1-7`/`libclang-7-dev`

Could not test with version 8.

With `libclang1-9`/`/libclang-9-dev`, build fails with:

```
$ ninja                                                                      
[658/688] Generating interface                                                                                          
FAILED: sandboxed_api/examples/sum/lib/sum-sapi.sapi.h                                                                 
cd /home/REDACTED/sandboxed-api_cb_build/sandboxed_api/examples/sum/lib && /usr/bin/python3.7 -B /home/REDACTED/sandboxed-api_cb/sandboxed_api/tools/generator2/sapi_generator.py --sapi_name=Sum --sapi_out=sum-sapi.sapi.h --sapi_embed
_dir=/home/REDACTED/sandboxed-api_cb_build/sandboxed_api/examples/sum/lib --sapi_embed_name=sum-sapi --sapi_functions=sum,sums,addf,sub,mul,divs,muld,crash,violate,sumarr,testptr,read_int,sleep_for_sec,sumproto --sapi_ns= --sapi_in=/hom
e/REDACTED/sandboxed-api_cb/sandboxed_api/examples/sum/lib/sum.c,/home/REDACTED/sandboxed-api_cb/sandboxed_api/examples/sum/lib/sum_cpp.cc
Traceback (most recent call last):            
  File "/home/REDACTED/sandboxed-api_cb/sandboxed_api/tools/generator2/sapi_generator.py", line 73, in <module>                                                                                                                             
    app.run(main)                       
  File "/home/nomad/.local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/nomad/.local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/REDACTED/sandboxed-api_cb/sandboxed_api/tools/generator2/sapi_generator.py", line 62, in main
    FLAGS.sapi_embed_dir, FLAGS.sapi_embed_name)
  File "/home/REDACTED/sandboxed-api_cb/sandboxed_api/tools/generator2/code.py", line 725, in generate
    related_types = self._get_related_types(function_names) 
  File "/home/REDACTED/sandboxed-api_cb/sandboxed_api/tools/generator2/code.py", line 784, in _get_related_types
    for f in self._get_functions(func_names):
  File "/home/REDACTED/sandboxed-api_cb/sandboxed_api/tools/generator2/code.py", line 751, in _get_functions
    f for f in translation_unit.get_functions()
  File "/home/REDACTED/sandboxed-api_cb/sandboxed_api/tools/generator2/code.py", line 605, in get_functions
    self._process()
  File "/home/REDACTED/sandboxed-api_cb/sandboxed_api/tools/generator2/code.py", line 582, in _process
    if cursor.kind.is_declaration():
  File "/usr/local/lib/python3.7/dist-packages/clang/cindex.py", line 1517, in kind
    return CursorKind.from_id(self._kind_id)
  File "/usr/local/lib/python3.7/dist-packages/clang/cindex.py", line 636, in from_id
    raise ValueError('Unknown template argument kind %d' % id)
ValueError: Unknown template argument kind 440
```

**Comment by cblichmann** [comment]
Workaround: Instead of using `pip3`/`pip` to install the Clang Python bindings, copy the `clang` directory from [upstream LLVM](https://github.com/llvm/llvm-project/tree/master/clang/bindings/python/) to your local home directory into `~/.local/lib/python3.8/site-packages/clang` (adjust for your version of Python).

**Comment by cblichmann** [comment]
Commit 405cc0068328b9c66d4c54940d7a178352f602e2 works around the issue in Python code. This is not ideal, but fixes the issue for now.

**Comment by cblichmann** [comment]
Fixed in more recent commits. The Python generator will be replaced by a Clang based one soon.

**Comment by tmmass** [comment]
mint 19.1 (it still fails with latest llvm)
"sudo apt-get install libclang-7-dev"   ( this fixes it though, as noted above)
